### ISSUE TITLE
i can't press Ctrl - C

### ISSUE THREAD

**Issue by TRAlruwaily** [mjavadhpour/telegram-member-inviter#5]
i can't press Ctrl - C why ?? i use exe and powershell

**Comment by mjavadhpour** [comment]
I think it is related to the binary package, because the python script works fine. Maybe remove --console flag in build.py can solve the problem. I will test it. thanks.

**Comment by mjavadhpour** [comment]
Just Remove the usage of CTRL + C to switch clients and replace it with `s`. the `SIGINT` can be used to shut down the application gracefully.
