### ISSUE TITLE
[BUG] Handle FloodWaitError 

### ISSUE THREAD

**Issue by khalilpish** [mjavadhpour/telegram-member-inviter#7]
I get:
` [ERROR] A wait of 3595 seconds is required (caused by InviteToChannelRequest)`
But I expected to switch to another client when current client is banned by telegram.

**Comment by mjavadhpour** [comment]
Fixed on v1.1.7

**Comment by khalilpish** [comment]
ohhhhh    no
What is happening? 
What are you fu*cking doing? 
Previous versions did not have a dick crash

**Comment by mjavadhpour** [comment]
Fixed on v1.1.8
